# Generated by Django 4.0.2 on 2022-02-27 13:05

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('userid', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
