# Generated by Django 4.0.2 on 2022-02-27 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userid', '0003_alter_userprofile_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
