# Generated by Django 4.0.2 on 2022-03-01 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userid', '0007_alter_userprofile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='picture',
        ),
    ]
